image: node:10.15.3
pipelines:
  default:
     - step:
           name: Run tests
           script: 
             - npm install
             - npm run test
           artifacts: 
             - application.tar.gz
     - step:
           name: Create artifact
           script: 
             - git archive --format=tar.gz master -o application.tar.gz 
           artifacts: 
             - application.tar.gz
     - step:
           name: Deploy to heroku
           deployment: production
           caches:
             - node
           script:
             - pipe: atlassian/heroku-deploy:1.2.1
               variables:
                 HEROKU_API_KEY: $HEROKU_API_KEY
                 HEROKU_APP_NAME: $HEROKU_APP_NAME
                 ZIP_FILE: "application.tar.gz"
                 WAIT: 'true'